
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class mainWindow extends JFrame {

    public final drawWindow draw;
    public final controlWindow control;
    public final About about;
    
    /*
    * Kiểu giao diện hiện tại
    *   - True: giao diện tối
    *   - False: giao diện sáng
    */
    private boolean themes = false;
    
    /*
    * Danh sách mã màu của từng giao diện 1, 2, 3, 4, 5 lần lượt là
    *   - 1: Màu nền khung hình vẽ
    *   - 2: Màu viền khung hình vẽ
    *   - 3: Màu vạch đo thước dọc
    *   - 4: Màu nét vẽ khung đồ thị
    *   - 5: Màu nền ứng dụng
    *   - 6: Màu thước
    */
    private Color light[] = new Color[]{new Color(255, 248, 220), Color.gray, new Color(0, 75, 75), Color.black, Color.white, Color.black};
    private Color dark[] = new Color[]{new Color(20, 20, 20), Color.LIGHT_GRAY, new Color(0, 175, 0), Color.white, Color.lightGray, Color.white};

    public mainWindow() {
        initComponents();
        getContentPane().setLayout(new BoxLayout(getContentPane(), BoxLayout.LINE_AXIS));
        pack();
        setSize(1200, 550);
        setTitle("Nhiễu Xạ Ánh Sáng");
        setLocationRelativeTo(null);
        setBackground(new Color(250, 250, 250));
        setResizable(false);
        setPreferredSize(new Dimension(1200, 550));
        image icon = new image("icon.png", 64, 64);
        this.setIconImage(icon.img);

        draw = new drawWindow(this);
        about = new About(this, true);
        control = new controlWindow(this);
        add(draw);
        add(control);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        btnAbout.setText("Thông tin");
        btnAbout.setName(""); // NOI18N
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        jMenuBar1.add(btnAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //<editor-fold desc="Sự kiện menu">
    private void btnAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseClicked
        btnAbout.setSelected(false);
        drawDialog();
    }//GEN-LAST:event_btnAboutMouseClicked

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setSelected(true);
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setSelected(false);
    }//GEN-LAST:event_btnAboutMouseExited
    //</editor-fold>

    private void drawDialog() {
        //JOptionPane.showMessageDialog(this, text, label, JOptionPane.INFORMATION_MESSAGE);
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAbout;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public boolean getThemes() {
        return themes;
    }

    public void setThemes(boolean themes) {
        this.themes = themes;
    }

    public Color[] getColor() {
        //Trả về bảng màu của giao diện hiện tại
        if (themes) {
            return dark;
        }
        return light;
    }
}
